package com.doconnect.entity;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import lombok.Data;

@Data // Lombok annotation to generate getters, setters, equals, hashCode, and toString
public class Answer {

    private Long id; // Unique identifier for the answer
    private Long questionId; // Links this answer to a specific question
    private Long userId; // ID of the user who provided the answer
    private String content; // The content/body of the answer
    private boolean approved; // Flag to check if the answer is approved by admin
    private LocalDateTime createdAt; // Timestamp when the answer was created

    // Extra fields for richer functionality
    private int likes = 0; // Number of likes for the answer
    private List<String> comments = new ArrayList<>(); // List of user comments on the answer

    public Answer() {} // Default constructor

    // Getters & Setters (auto-generated by Lombok @Data, but can be customized if needed)
}
